import type { Tool } from './types'

export const TOOLS: Tool[] = [
  { id: 'change-pressure',       slug: '/diagnostics/change-pressure',       title: 'Change Pressure Index',    tagline: 'How much change pressure is your organisation under?',           description: 'Estimate investment, adoption risk, readiness, and expected productivity impact for a specific initiative.',                              icon: 'pressure',      audience: 'enterprise', timeEstimate: '5–7 min',  questionCount: 8,  outputs: ['Pressure score','Readiness score','Adoption risk'],      enterpriseFilters: ['all','preparing','struggling'] },
  { id: 'initiative-overload',   slug: '/diagnostics/initiative-overload',   title: 'Initiative Overload',      tagline: 'Are you running more change than your organisation can absorb?', desc: 'Map your active change portfolio against bandwidth. Surface sequencing risk and capacity constraints.',                    icon: 'overload',      audience: 'enterprise', timeEstimate: '7–10 min', questionCount: 12, outputs: ['Overload score','Bandwidth remaining','Sequencing risk'], enterpriseFilters: ['all','portfolio'] },
  { id: 'sponsor-effectiveness', slug: '/diagnostics/sponsor-effectiveness', title: 'Sponsor Health Check',     tagline: 'Is your leadership sponsoring this change or just approving it?', description: 'Assess sponsor health across five dimensions: visibility, participation, communication, coalition, and resistance management.',                    icon: 'sponsor',       audience: 'enterprise', timeEstimate: '5–7 min',  questionCount: 10, outputs: ['Sponsor health score','Dimension breakdown'],          enterpriseFilters: ['all','struggling','leadership'] },
  { id: 'readiness-scan',        slug: '/diagnostics/readiness-scan',        title: 'Readiness Scan',           tagline: 'Are you ready to transform or just ready to start?',           description: 'Assess readiness across leadership alignment, change capability, culture and trust, strategic clarity, and track record.',                          icon: 'readiness',     audience: 'enterprise', timeEstimate: '7–10 min', questionCount: 12, outputs: ['Readiness score','Five-dimension breakdown'],          enterpriseFilters: ['all','preparing'] },
  { id: 'communication-clarity', slug: '/diagnostics/communication-clarity', title: 'Communication Audit',      tagline: 'Are you communicating change well or just communicating a lot?', description: 'Evaluate message clarity, channel effectiveness, two-way dialogue, and audience targeting.',              icon: 'communication', audience: 'enterprise', timeEstimate: '5–7 min',  questionCount: 10, outputs: ['Clarity score','Channel effectiveness','Dialogue quality'], enterpriseFilters: ['all','struggling','communication'] },
  { id: 'people-impact',         slug: '/diagnostics/people-impact',         title: 'People Impact',            tagline: 'Who is actually affected by this change and how much?',          description: 'Map workforce impact across scale, depth, vulnerability, and support readiness.',                    icon: 'people',        audience: 'enterprise', timeEstimate: '5–7 min',  questionCount: 9,  outputs: ['Impact level','Vulnerability map','Support readiness'],   enterpriseFilters: ['all','struggling','preparing'] },
  { id: 'business-friction',     slug: '/diagnostics/business-friction',     title: 'Business Friction',        tagline: 'Where is your business losing energy?',                          description: 'Identify communication friction, workflow bottlenecks, accountability gaps, and operational drag.',                                               icon: 'friction',      audience: 'sme',        timeEstimate: '5–7 min',  questionCount: 11, outputs: ['Friction score','Biggest friction area','Priorities'],      smeFilters: ['all','overwhelm','communication','leadership'] },
  { id: 'operational-overwhelm', slug: '/diagnostics/operational-overwhelm', title: 'Operational Overwhelm',    tagline: 'Is your business too busy to move forward properly?',            description: 'Assess overwhelm, reactive work patterns, admin overload, context switching, and decision fatigue.',                                               icon: 'overwhelm',     audience: 'sme',        timeEstimate: '5–7 min',  questionCount: 9,  outputs: ['Overwhelm score','Burnout risk','Capacity pressure'],       smeFilters: ['all','overwhelm','burnout','growth'] },
  { id: 'team-clarity',          slug: '/diagnostics/team-clarity',          title: 'Team Clarity',             tagline: 'Does your team actually know what matters most?',               description: 'Measure communication clarity, role clarity, expectations, accountability, and alignment.',                                                        icon: 'team',          audience: 'sme',        timeEstimate: '5–7 min',  questionCount: 9,  outputs: ['Clarity score','Alignment gaps','Communication risks'],     smeFilters: ['all','communication','leadership','burnout'] },
  { id: 'workplace-energy',      slug: '/diagnostics/workplace-energy',      title: 'Workplace Energy',         tagline: 'What is draining energy inside your business?',                 description: 'Assess morale, workload sustainability, recognition, clarity, and emotional fatigue.',                                                             icon: 'energy',        audience: 'sme',        timeEstimate: '5–7 min',  questionCount: 9,  outputs: ['Energy score','Burnout indicators','Team pressure areas'],   smeFilters: ['all','burnout','growth','customer'] },
  { id: 'simplicity-score',      slug: '/diagnostics/simplicity-score',      title: 'Simplicity Check',         tagline: 'How unnecessarily complex is your business?',                   description: 'Measure process complexity, unnecessary approvals, duplicated work, tool overload, and operational clutter.',                                       icon: 'simplicity',    audience: 'sme',        timeEstimate: '5–7 min',  questionCount: 9,  outputs: ['Simplicity score','Complexity drivers','Friction map'],     smeFilters: ['all','overwhelm','growth','customer'] },
]

export const getToolById = (id: string) => TOOLS.find(t => t.id === id)
export const ENTERPRISE_TOOLS = TOOLS.filter(t => t.audience === 'enterprise')
export const SME_TOOLS = TOOLS.filter(t => t.audience === 'sme')
